### ISSUE TITLE
Feature request: Send deep sleep command to display

### ISSUE THREAD

**Issue by onkelcommy** [jjwbruijn/OpenEPaperLink#105]
It would be nice to be able to send at "Deep sleep" command from the web ui like the "Reboot", "Scan channels" and "Clear settings" send commands.

This could be used to "disable" unused displays and make sure they don't join an AP before the batteries is re-inserted.

**Comment by jjwbruijn** [comment]
added here: https://github.com/jjwbruijn/OpenEPaperLink/commit/e457475ea75711f4e5747a1e9e473953470b7017

**Comment by jjwbruijn** [comment]
done, https://github.com/jjwbruijn/OpenEPaperLink/commit/0cbb9e770e63879891d4d760ba24d309fd870452
