### ISSUE TITLE
Feature request: Periodic update besides interval in content manager

### ISSUE THREAD

**Issue by onkelcommy** [jjwbruijn/OpenEPaperLink#106]
It would be great to be able to specify a periodic update besides the current "Interval" settings in the web ui for content with interval like "ImageUrl", "RSSFeed", "Calendar" and "json template".

Possible periods could be "Daily" (updated at midnight), "Hourly" (updated at the start of the hour) and "30 minutes" (updated at 00/30 minute) etc. Just a simple dropdown not full crontab mode :-)

This would allow displays to update time sensitive content at the start of a period and not by a random interval.

Example displaying the current electricity price for the current hour - updated every hour at XX:00
![electricity-prices](https://github.com/jjwbruijn/OpenEPaperLink/assets/17876344/3c429003-79ed-4de3-b0b6-0e0671273955)

**Comment by nlimper** [comment]
Added.
If you enter a negative value for the interval, it gets aligned. For example, -60 will refresh every hour at :00
