### ISSUE TITLE
AP info page not updated correctly

### ISSUE THREAD

**Issue by coelner** [jjwbruijn/OpenEPaperLink#109]
**Describe the bug**
The AP info page with the current IP is not updated correctly. It is not always the case.
the AP is running the 1.8 release with a 0x0017 firmware

**To Reproduce**
1. run the esp32
2. loose the wifi connection/get a new ip
3. see the old IP/not the "connect wifi AP" info page

**Expected behavior**
A correctly shown AP info page with the current IP or wifi AP connect page.
A "AP reboot" triggers the redraw. AFAIK the UI has the problem that you can not select the needed JSON template, because it is not a file.

**Additional context**
[Add any other context about the problem here.](https://github.com/jjwbruijn/OpenEPaperLink/blob/0cbb9e770e63879891d4d760ba24d309fd870452/ESP32_AP-Flasher/src/contentmanager.cpp#L1201C56-L1201C57)

Maybe the check for `isConnected();` is better here.

**Comment by nlimper** [comment]
Thank for the bug report. The AP info page was just temporaty. It's all fixed already, together with some other nice improvements, coming up in the next commit.
