### ISSUE TITLE
Feature request: drag and drop support for json templates

### ISSUE THREAD

**Issue by PieterBoeren** [jjwbruijn/OpenEPaperLink#115]
Now that the web interface supports drag and drop for image files, could the same be added for json templates? I think it would be quite handy to be able to drop a template with some vars in it, and update the variables via (for example) something like Home Assistant.

**Comment by nlimper** [comment]
good idea. I will add it later this week.

**Comment by nlimper** [comment]
done, https://github.com/jjwbruijn/OpenEPaperLink/commit/46fb23b70f1a7f403a12f1959b9636ce4ccf69a5
