### ISSUE TITLE
Feature request: invert colors

### ISSUE THREAD

**Issue by orichienal** [jjwbruijn/OpenEPaperLink#133]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
it would be nice if you could invert the displayed, e.g. at the weather data

**Describe alternatives you've considered**

**Additional context**

**Comment by nlimper** [comment]
nice idea. I can work on that. It can take a while before I implement it, but it's on my list. :-)

**Comment by nlimper** [comment]
done
https://github.com/jjwbruijn/OpenEPaperLink/commit/db80d23b52cf1899e9c4401b4c2b36419fd9ceb4
