### ISSUE TITLE
Readme issue - Tag Flasher directory

### ISSUE THREAD

**Issue by phpsystems** [jjwbruijn/OpenEPaperLink#140]
**Describe the bug**
Url issue on the readme in the Tag Flasher directory

**To Reproduce**
1. Go to Tag_flasher'
2. Click on 'install.openepaperlink.nl'
3. See error

**Expected behavior**
A clear and concise website for flashing the s2.

**Additional context**
Url might be incorrect, perhaps it should be install.openepaperlink.de ?

**Comment by jonasniesner** [comment]
Thank you for informing us about this typo
