### ISSUE TITLE
remember deep sleep state

### ISSUE THREAD

**Issue by coelner** [jjwbruijn/OpenEPaperLink#145]
**Describe the bug**
After sending a tag into deep sleep, it gets recognized as a "timeout" one , which is misleading.

**To Reproduce**
send tag to deep sleep and wait.

**Expected behavior**
group those tags by a separate state and individual icon

**Screenshots**
N/A

**Additional context**

**Comment by nlimper** [comment]
Nice suggestion. I will improve the behaviour a bit.

**Comment by nlimper** [comment]
fixed
https://github.com/jjwbruijn/OpenEPaperLink/commit/a4e19b19ab78218cd3e6251c9de081c3aafeeb5a
