### ISSUE TITLE
Feature request: BOM File for JLCPCB

### ISSUE THREAD

**Issue by bluenazgul** [jjwbruijn/OpenEPaperLink#151]
According to the Gerber File, could you provide an BOM File? Maybe this way it would be possible to Order an prebuild Board via JLCPCB

**Comment by jonasniesner** [comment]
This repo includes multiple PCBs, with one do you want the BOM for?

**Comment by jonasniesner** [comment]
Closing this issue because there was no response in a long time. If a specific BOM is required, feel free to reopen.

**Comment by superseppl** [comment]
How about the BOM and placements file for https://github.com/OpenEPaperLink/Hardware/tree/main/Yellow%20AP%20by%20ATC1441?
