### ISSUE TITLE
Docs request: expected battery life 

### ISSUE THREAD

**Issue by Fabian-Schmidt** [jjwbruijn/OpenEPaperLink#153]
Hi,
Thanks for this awesome project.
I understand that you optimised the solution for maximum battery life time of the tags. What I have not found is the expected best (and maybe worst case)  battery life depending on display type. Are we talking days, weeks or maybe months?
Could you please add some sentences to the Wiki about it.

Cheers Fabian

**Comment by crackers81** [comment]
That would depend on how often you update the tags. 
Every minute = weeks
every hour = months
