### ISSUE TITLE
Support Brave browser

### ISSUE THREAD

**Issue by alex3305** [jjwbruijn/OpenEPaperLink#156]
**Describe the bug**
Cannot use OpenEpaperLink web installer on [Brave Browser](https://brave.com/nl/).

**To Reproduce**
1. Go to https://install.openepaperlink.de/ on Brave
2. See error; _"Sorry, your browser is not yet supported! Please try on Desktop Chrome or Edge."_

**Expected behavior**
That I can use the installer on (Chromium-based) compatible browsers.

**Comment by atc1441** [comment]
https://github.com/brave/brave-browser/issues/24404

**Comment by alex3305** [comment]
Thank you ❤️ Completely missed that 🤦 .

For future reference, enabling can be done with `brave://flags/#brave-web-serial-api`.
