### ISSUE TITLE
Not possible to set Helsinki timezone

### ISSUE THREAD

**Issue by jurasjo** [jjwbruijn/OpenEPaperLink#161]
**Describe the bug**
Hi,
looks like it is not possible to set Helsinki as local timezone. 
When I try to set Helsinki and save, then after refreshing the page Athens, Greece is set.
Other values work as expected. Looks like the only problem is with Helsinki.

**To Reproduce**
1. Go to Settings.
2. Choose Helsinki for 'Local time zone' and save.
3. Refresh the page.
4. Athens, Greece is set instead of Helsinki.

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/19259405/ef0bdb99-4ee5-45b3-b779-f4df84243f6f)

5. Contents of the apconfig.json file confirms that:

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/19259405/5221e5b5-812a-49eb-b24f-88c04881604a)

**Expected behavior**
Helsinki should be set as 'Local time zone'.

**Comment by nlimper** [comment]
Athens has the same time zone as Helsinki. It's just a name. :-)
