### ISSUE TITLE
M3-tags not reporting firmware-version

### ISSUE THREAD

**Issue by svenove** [jjwbruijn/OpenEPaperLink#168]
**Describe the bug**
The M3-tags report "0" as their firmware-version in tagDB.json

**To Reproduce**
1. Add a M3-tag
2. Look in /current/tagDB.json and see "ver: 0"

**Expected behavior**
Version should be read correctly.

**Comment by jonasniesner** [comment]
With the newer firmware versions, the version is displayed.
