### ISSUE TITLE
AP not updating tags

### ISSUE THREAD

**Issue by paveldn** [jjwbruijn/OpenEPaperLink#171]
**Describe the bug**
Everything worked perfectly but AP suddenly stopped updating tag images. No changes where made. Tags are communicating but every time after updating the tag image (from home assistant integration or manually from AP web interface). For every update attempt, I see the log records:
17:57:12 Resending image //current/0000021F7DC13B12.raw
17:57:12 new image is the same as current or already pending image. not updating tag.
17:57:11 Updating 0000021F7DC13B12
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nlimper** [comment]
So, it appears the new image cannot be written to the file system. I can think of two possible situations:
- the file system is full. Especially on eso32-s2 based AP's, file system space is *really* tight. Delete all unneccesairy files using the file editor (`/edit`).
- or, for some reason, the file system is corrupted, sometimes cause littlefs to refuse to write to it. Reflash the file system. If you use vscoce/platformio, use 'upload filesystem image'. Or if you don't, the easiest method is to reflash everything, using install.openepaperlink.de . Your filesystem will be overwritten, so backup any files you want to keep before doing this.
good luck!

**Comment by paveldn** [comment]
Thanks. Not sure if was it corruption or full flash but reflashing helped.
Thanks for the amazing work!
