### ISSUE TITLE
Feature request: tag resolution in web interface

### ISSUE THREAD

**Issue by Fettkeewl** [jjwbruijn/OpenEPaperLink#172]
**Is your feature request related to a problem? Please describe.**
Remembering device display resolution 

**Describe the solution you'd like**
Show tag display resolution on AP "Active tags" webpage / Show in device info for HA 

**Describe alternatives you've considered**
Note it down myself

**Additional context**
![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/25577040/6ba68d48-d134-47da-93b7-50b46bc5a908)
![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/25577040/1a24c89c-10fc-4792-91b5-df426e96af80)

**Comment by jonasniesner** [comment]
Can you please elaborate on what you want to achieve with this feature request? Do you want the resolution for all tag types?

**Comment by nlimper** [comment]
In the webinterface, it’s currently impossible to quickly see the resolution of a connected tag. I already planned to add it somewhere.

**Comment by nlimper** [comment]
done https://github.com/jjwbruijn/OpenEPaperLink/commit/424cf2faf6772dba38a2e1c2f7706bc658536467
