### ISSUE TITLE
Orphaned Tag??

### ISSUE THREAD

**Issue by mattfox27** [jjwbruijn/OpenEPaperLink#175]
Is this an orphaned tag?  All my tags are setup not sure what this is?  I cannot remove it

![orphaned tag](https://github.com/jjwbruijn/OpenEPaperLink/assets/6801877/f2bac0bf-36c5-430d-9bf7-dd4f24c8985e)

**Comment by nlimper** [comment]
It's some random noise that was picked up and interpreted as a unknown tag. Until know, you cannot delete it from the web interface, that's a bug I want to solve so I keep this one open.
In the meantime, if you want to remove it: go to the file editor in /edit, and change the file /current/tagDB.json to remove the tag. After uploading the changes, power cycle the AP (by pulling the plug), as using the 'reboot' button rewrites the tagDB from memory.

**Comment by mattfox27** [comment]
> It's some random noise that was picked up and interpreted as a unknown tag. Until know, you cannot delete it from the web interface, that's a bug I want to solve so I keep this one open. In the meantime, if you want to remove it: go to the file editor in /edit, and change the file /current/tagDB.json to remove the tag. After uploading the changes, power cycle the AP (by pulling the plug), as using the 'reboot' button rewrites the tagDB from memory.

will do...thanks

**Comment by nlimper** [comment]
I fixed the web interface, it's now possible again to delete unknown tags by right clicking. (in latest commit; will be included in next release)

**Comment by mattfox27** [comment]
Awesomes...thank you
