### ISSUE TITLE
Updated SOLUM 1.54 tag to FW .24, web UI reports 'FW: 36'

### ISSUE THREAD

**Issue by Calimerorulez** [jjwbruijn/OpenEPaperLink#176]
I just discovered the new tag firmware .24 in the repo. Updated a 1.54 tag with it, now the web UI reports 'FW: 36' :)

Same goes for the 2.9 SOLUM.

**Comment by jonasniesner** [comment]
A bit of context:
The tag shows the firmware in HEX
The AP shows it in Dec 

Should be a trivial fix though
Maybe the fix should be implemented in the web part to keep the API stable

**Comment by Calimerorulez** [comment]
Thank you for the clarification. I didn't understand why at first, because on FW .19 and .22 the web UI showed .19 and .22 too.

**Comment by jonasniesner** [comment]
Fixed by 5973607
