### ISSUE TITLE
Don't suggest IEEE 802.15.4 channel 27 on Mini-AP v3 (ESP32-C6)

### ISSUE THREAD

**Issue by CrazyCoder** [jjwbruijn/OpenEPaperLink#178]
This channel doesn't seem to work on C6 hardware. Tags will never connect to AP.

If you also disable "Scan for AP on timeout", it's possible to brick the tags.

A workaround if you didn't disable this option is to set the AP channel back to the default and let tags reconnect on timeout (may take 10-30 minutes).

This happened to me with fw 19 tags, see https://discord.com/channels/717057001594683422/1184738775297953842.

**Comment by nlimper** [comment]
fixed in upcoming release
