### ISSUE TITLE
Feature request: "No updates between" per-tag

### ISSUE THREAD

**Issue by gcormier** [jjwbruijn/OpenEPaperLink#180]
Right now, putting tags to sleep for the night is a global option.

It would be nice to decide this per-tag. My example use case

- I have some tags showing exterior temperature for the purposes of deciding which jacket to wear. This is not really needed for me later in the evening.
- I have other tags showing interior information - I would want this visible during all waking hours, which will be a longer period of time compared to the above tags.

**Comment by nlimper** [comment]
These are micro-optimisations... The tags are very battery-efficient already, e.g. the weather displays will already sleep for a long time between updates (is you set 'Maximum sleep' to 1 hour in the tag config. The tags will sleep longer if possible, but short if needed).
