### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by nigels0** [jjwbruijn/OpenEPaperLink#182]
**Is your feature request related to a problem? Please describe.**
No - its an enhancement of function

**Describe the solution you'd like**
Really, its an enhancement to the draw function - to allow reverse image, so you can have, say white text in a red background - ideally, have an option when drawing text to say what the background is.

**Comment by nigels0** [comment]
Nevermind, managed to do it with the following code:

`left, top, right, bottom = draw.textbbox((x,y) , args.line1, font=font)
draw.rectangle((left-2, top-5, right, bottom+5), fill = 'red')`

**Comment by nlimper** [comment]
I don’t know which language you are writing the code, but it’s not something within OpenEpaperLink. 😊

**Comment by nigels0** [comment]
Right - it is in python using the pillow library. Would be great to have a background option antway.

**Comment by nlimper** [comment]
The text is not antialiased (because the epaper only can display white/black/red without shades). So, if you use the json template, you can just draw a red box, and use white text.
