### ISSUE TITLE
Corrupted Display for FW Version v0.24 with SSD1619 Based Tags

### ISSUE THREAD

**Issue by Jebsta** [jjwbruijn/OpenEPaperLink#183]
**Describe the bug**
After updating the Firmware on my ST-GR2900 and ST-GR1600 Tags the content on them sometimes corrupted itself.
I only have those types of tags, so don't know if it only happens on this type of tag.
Some of the tags even "crashed" and never connected with the AP. Only after reset and then only until the next crash.

**To Reproduce**
1. Update the Tags to v0.24
2. Wait for the screen to show a new image
3. See the error (maybe just after some refreshes)

**Expected behavior**
It should just show the image/content

**Screenshots**
![IMG20231214210823__](https://github.com/jjwbruijn/OpenEPaperLink/assets/67825152/d53e49c9-eb7a-4b25-8a0b-a6d5aa3cf42d)
![IMG20231214214624](https://github.com/jjwbruijn/OpenEPaperLink/assets/67825152/bf9a0151-2630-4364-b936-33099faa8e64)
![IMG20231215033047](https://github.com/jjwbruijn/OpenEPaperLink/assets/67825152/db9296e0-b82b-4064-8e18-83ea454d4e7f)

**Comment by jonasniesner** [comment]
@Jebsta There is a test version on the discord that might fix this, Do you want to try it?

**Comment by jonasniesner** [comment]
Should be fixed by ab8cb39
