### ISSUE TITLE
Tag would get stuck on the update to v0.24

### ISSUE THREAD

**Issue by Jebsta** [jjwbruijn/OpenEPaperLink#184]
**Describe the bug**
When updating the Firmware on my ST-GR2900 and ST-GR1600 Tag to v0.24 some of them would get stuck on the "Updating" screen. Some of them with glitchy image. The Glitchy images show maybe an old image. If you look at the top left one you may see the words "CASHEWKERNE" and in big lettering "2.49". I used the Tag before and never saw that Image.

**To Reproduce**
1. Update to v0.24 (OTA)
2. See the error (Did only occur ~30% of the time)

**Expected behavior**
It should only show the "Updating" screen for a few seconds and then connect to the AP

**Screenshots**
![IMG20231214203622__](https://github.com/jjwbruijn/OpenEPaperLink/assets/67825152/eab23c27-811d-4bbb-84f7-99b59734b5ce)

![IMG20231214203622_](https://github.com/jjwbruijn/OpenEPaperLink/assets/67825152/ccab7bec-188d-414c-8724-774c5a5cd43e)

**Comment by jonasniesner** [comment]
Should be fixed by ab8cb39
