### ISSUE TITLE
[Question] Changing AP channel, will tags follow?

### ISSUE THREAD

**Issue by Calimerorulez** [jjwbruijn/OpenEPaperLink#185]
Hi,

Currently running an AP on channel 11, and I want to change it to a higher one.
Will the tags follow the channel change on the AP? Or do I have to change the tags configuration before the change of the channel? I saw an option in the tag config to periodically scan for AP's (roaming).

**Comment by nlimper** [comment]
The tags will follow eventually, after about half a day. No other configuration needed. If they cannot find the AP anymore, eventually they will do a new network scan.

The 'roaming' setting in the tag config (works only on fw ver 0022 and higher, not on the default 0019 fw) causes the tag to do a network scan much more often, even if the AP is still connected. It is to be used in very specific situations, and affects the battery life a lot. So keep it disabled.
