### ISSUE TITLE
Tags are waiting for data but never update

### ISSUE THREAD

**Issue by jelloj1** [jjwbruijn/OpenEPaperLink#187]
**Describe the bug**
Tags are connected to mini-AP - I can reboot them from webpage, but they never update with any content - in the logs it keeps saying "blocked request" and the AP will contstantly reboot

**To Reproduce**
Try to update a tag
AP reboots constantly
Tag eventually times out

**Expected behavior**
Expect tag to update per the instructional video

**Screenshots**

**Additional context**
Purchased both tags and mini-AP kit off Tinde - tags seem to have version 1.9 - learned the "battery" method to get them to boot up and they work fine, find the AP, show up in the webbrowser, but say waiting for data.  everythings is soldered correctly on AP (including the jumper) and it seems to update just fine.  Tried different zigbee channels since I have Phillips Hue on channel 20

**Comment by nlimper** [comment]
Not enough information. What kind of content are you sending? If you're uploading an image, make sure you use the exact right resolution, jpeg, baseline (no progressive). First try to use a simple content type (like 'count hours').
If it's not working, provide the output of the serial terminal.

**Comment by jelloj1** [comment]
I tried sending all the different content, but to get the logs, I just tried to send the current date.   - Here is a screen shot of the web logs and the attached file is the serial log.  
![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/31767762/5ffe1f5e-fa06-487e-93b5-168a701a6909)

[esp-web-tools-logs.txt](https://github.com/jjwbruijn/OpenEPaperLink/files/13798911/esp-web-tools-logs.txt)

For reference x131 is the AP and xB1A is the tag I used in this example.

**Comment by nlimper** [comment]
This behaviour will show if the segmented tag is not connected to VCC. It is back-fed by the other pins so it works a bit, but the power is not strong enough for actual sending of an image.

You probably forgot to solder the little blob for connecting VCC:
![IMG_4032](https://github.com/jjwbruijn/OpenEPaperLink/assets/4137036/c4584a73-7325-4b20-bb7f-5dc3fc3728c9)
Or, if the blob is there, the VCC pad is not connected successfully to the segmented tag.

**Comment by jelloj1** [comment]
Ok - I did jumper the VCC - but i will poke around and make sure the solder job is good.

**Comment by jelloj1** [comment]
That was it - I resoldered everything and it worked - thanks for your help!
