### ISSUE TITLE
No red color on M2 v0025

### ISSUE THREAD

**Issue by jurasjo** [jjwbruijn/OpenEPaperLink#189]
**Describe the bug**
After flashing tags with the M2 v0025 firmware, there is no red color. What is supposed to be red font is simply black. Looks like also what is dispalyed, is not sharp like it should be.

**To Reproduce**
I use for example Weather Forecast option, now we have minus temperatures and on v0024, temperatures are red and after flashing to v0025, the same temp is black.

**Expected behavior**
Red color should be displayed.

**Comment by psfales** [comment]
I'm seeing the same thing, I think.    
![PXL_20240109_012531086](https://github.com/jjwbruijn/OpenEPaperLink/assets/11315210/66a8307d-7018-493f-b450-0980a73e7c8a)
![PXL_20240109_013119385](https://github.com/jjwbruijn/OpenEPaperLink/assets/11315210/ec9dcaad-eace-4d8a-8da6-40b0100efe1a)
The all black photo is what I get with v25.   The other photo with the red is after switching back to v22 and how it is supposed to look.

Also, if you look in the lower right of the v25 image where it shows the time, you can see faint traces of an earlier value.    I think this might be related to the lack of sharpness that the OP reported. 

However, it's not always consistent.     When I first installed v25, I know that I was able to see the red (for example, when I tested with "Current Date" ) I could see the red.   It was only after running for several days that I realized this particular display was not displaying any red.

**Comment by jurasjo** [comment]
Look like M2 v0026 version is out. I have installed it. Red color and sharpeness are back.

**Comment by jonasniesner** [comment]
Fixed with v0026
