### ISSUE TITLE
ARM_Tag_FW /OpenEPaperLink_TLSR needs a tc32_linux directory to fix builds process.

### ISSUE THREAD

**Issue by nethomas1968** [jjwbruijn/OpenEPaperLink#196]
**Describe the bug**
ARM_Tag_FW /OpenEPaperLink_TLSR needs a tc32_linux directory for builds to succeed.

**To Reproduce**
1. Go to ARM_Tag_FW /OpenEPaperLink_TLSR 
2. make

**Expected behavior**
Compilation should start

**Screenshots**
N/A

**Additional context**
Not really.

**Comment by nethomas1968** [comment]
No linux support planned !!!!

**Comment by jjwbruijn** [comment]
Rivers were cried. We take pull requests!
