### ISSUE TITLE
Feature request: Show update time on screen (small).

### ISSUE THREAD

**Issue by haselchen** [jjwbruijn/OpenEPaperLink#197]
Great work, Guys!

It would be an absolute must-have if the update time was shown at the bottom left or right of the screen. This way I can quickly see whether everything is OK with the AP.
Many users will probably say: you can do it yourself.
I think an implementation would be extremely helpful for all users.

**Comment by nlimper** [comment]
was already planned :-)
Finished it, in https://github.com/jjwbruijn/OpenEPaperLink/commit/3b294be08ae7cd48a34eff126adf5741ec3df5a4
(and in the next release)
