### ISSUE TITLE
Improve formatting for Google Calendar

### ISSUE THREAD

**Issue by psfales** [jjwbruijn/OpenEPaperLink#202]
**Is your feature request related to a problem? Please describe.**
If a Google Calendar entry is longer than one line, it wraps around and overwrites the next line.  (See photo for an example)

**Describe the solution you'd like**
Simplest would be just truncate the line at the right edge.  Nicer would be to use two (or more lines)  for the entry if necessary.  (The subsequent lines could be indented so they line of up with the first, rather than start at the left edge)

**Describe alternatives you've considered**
I could try to remember to keep the calendar entries short, but would prefer not to do that

**Additional context**
![PXL_20240113_025655946](https://github.com/jjwbruijn/OpenEPaperLink/assets/11315210/b4a6b7ce-1ab0-446d-a2b6-bfcd7f8cdd30)

**Comment by peterchs** [comment]
I truncate the event titles in the google calendar script to work around this wrapping.

Also the date in the top right doesnt adhere to the configured language.json "date_format" its always dd-mm-YYYY for me.

**Comment by nlimper** [comment]
Thanks for the report. I will fix it.

**Comment by peterchs** [comment]
Latest 2.5beta fixes date formatting, thanks.
Cant comment on the text wrapping events arent long enough.

**Comment by nlimper** [comment]
fixed. Long lines get truncated now.
(in upcoming commit/releases)
