### ISSUE TITLE
Alternate date formats for Google Calendar

### ISSUE THREAD

**Issue by psfales** [jjwbruijn/OpenEPaperLink#203]
**Is your feature request related to a problem? Please describe.**
Google Calendar dates are displayed as DD-MM.    In the US, the convention would by MM-DD (or MM/DD).   Similarly, the date in the top right is DD-MM-YYYY.  The US convention would be MM-DD-YYYY (but that one doesn't seem as critical for me)

**Describe the solution you'd like**
It's probably hard to provide a completely general solution, but perhaps a few common formats could be provided.  (Like the way the "Current Weather" page allows a choice of Fahrenheit or Celsius.)

**Comment by nlimper** [comment]
fixed date format for english language setting to mm/dd
https://github.com/jjwbruijn/OpenEPaperLink/commit/f00761db94415355f12223266a6768363465d77c
