### ISSUE TITLE
PCB for the S3_C6_NanoAP running an ESP32-S3 and ESP32-C6 Feature request: Providing the KiCAD files

### ISSUE THREAD

**Issue by TimSchimansky** [jjwbruijn/OpenEPaperLink#207]
**Is your feature request related to a problem? Please describe.**
A Gerber file is provided (as well as list of parts in the readme) This is not really enough to build the AP...

**Describe the solution you'd like**
Providing the KiCAD files to open the possibility to order a PCB from e.g. JLCPCB with component assembly.

**Describe alternatives you've considered**
Reverse engineering from the images, but its unclear, which components go where (the capacitors are not marked)

**Comment by ele0n** [comment]
I would also be interested in KICAD files or other working files with placement.

**Comment by atc1441** [comment]
See attachment, without guarantees :)
[pap.csv](https://github.com/jjwbruijn/OpenEPaperLink/files/14157086/pap.csv)
[bom.csv](https://github.com/jjwbruijn/OpenEPaperLink/files/14157087/bom.csv)

**Comment by TimSchimansky** [comment]
I will try this, thank you!
