### ISSUE TITLE
Feature request: Templates with Red colour in them on Black/White tags

### ISSUE THREAD

**Issue by Reletiv** [jjwbruijn/OpenEPaperLink#209]
**Is your feature request related to a problem? Please describe.**
Templates with Red text in them currently don't work on Black/White tags

**Describe the solution you'd like**
Making color in templates possibly optional

**Describe alternatives you've considered**
I considered letting the tag interpret Red input text as if it was black text

**Comment by nlimper** [comment]
Yeah, I will work on that. I will test the templates, maybe it works to do a pattern gray instead of the red color.

**Comment by nlimper** [comment]
fixed in upcoming release
