### ISSUE TITLE
Tag settings disappeared

### ISSUE THREAD

**Issue by seeers** [jjwbruijn/OpenEPaperLink#213]
**Describe the bug**
I have just compiled the current version from the repo and flashed it to my Mini AP (including filesystem image) 
Unfortunately it is no longer possible to set the content for a tag. Only an alias can be assigned. The dropdown for the content type has disappeared. 
![TagAlias](https://github.com/jjwbruijn/OpenEPaperLink/assets/16150580/a8ca2585-e4e8-4f4c-bbff-926853e04c18)

**Comment by nlimper** [comment]
Clear your browser cache. Your browser uses an old version of content_cards.json.
