### ISSUE TITLE
hanshow nebular problem

### ISSUE THREAD

**Issue by nikkisstuff** [jjwbruijn/OpenEPaperLink#216]
I have two hanshow nebular 3.5" displays both the same model but one or them the background colours are inverted 

![IMG_9503](https://github.com/jjwbruijn/OpenEPaperLink/assets/77486170/11356422-898e-4713-a90a-e5954084742b)

**Comment by nethomas1968** [comment]
I've heard that there are 2 chipsets used in these devices. Is it possible that you have one of each.
I suppose you might need to open up the back to get to see the little CPU board to look at the chip markings.

**Comment by nethomas1968** [comment]
Also, which of the Firmware directories in this repo have you used to get that far ? I've had little success with the ARM_Tag_FW/OpenEPapaerLink/TLSR but I can't get it to use the whole screen area.
What are you doing right that I'm not ?

**Comment by nikkisstuff** [comment]
This is the file i used https://github.com/jjwbruijn/OpenEPaperLink/blob/master/binaries/Tag/TLSR_HS_35_ALPHA.bin

I did open the tags and the board look the same. the chip is identical just branded "Hanshow"

**Comment by nikkisstuff** [comment]
Also I am running it via OpenEPaperLink-PyStation with a cc2531
