### ISSUE TITLE
Feature request: Support upload of lossless image format.

### ISSUE THREAD

**Issue by dreirund** [jjwbruijn/OpenEPaperLink#221]
### Is your feature request related to a problem? Please describe.

[The wiki says](https://github.com/jjwbruijn/OpenEPaperLink/wiki/Image-specifications) that the images which can be uploaded should be JPEG.

This is a bad choice:

* JPEG is designed for (quasi)continuous colour space. The tags have discrete colours (two, three or four). JPEG is not designed for that.
* JPEG creates artifacts.
* Lossless formats are _both_ smaller AND without artifacts with discrete colour space.

### Describe the solution you'd like

Support lossless image format.

Low level like pbm, high level like PNG, or embedded-friendly like QOI, or something else.

Your choice. But lossless.

**Comment by jjwbruijn** [comment]
You're a recordholder opening issues. Please let me know when you've forked this project and have built a version with all of your issues fixed.
