### ISSUE TITLE
Pinout needed m3 newton 9.7"

### ISSUE THREAD

**Issue by nikkisstuff** [jjwbruijn/OpenEPaperLink#227]
Is there a pinout for this display?

![IMG_9521](https://github.com/jjwbruijn/OpenEPaperLink/assets/77486170/d80f1b80-0f65-474f-8dbc-123a3aacb185)
![IMG_9522](https://github.com/jjwbruijn/OpenEPaperLink/assets/77486170/b36a4d35-d751-48a8-aabe-fde5445ac78d)
![IMG_9523](https://github.com/jjwbruijn/OpenEPaperLink/assets/77486170/32270405-cfac-4b49-8e6a-7f471c0b2e27)

**Comment by VstudioLAB** [comment]
The pinout is common for all M3 tags. 
You can see it here:
https://github.com/jjwbruijn/OpenEPaperLink/wiki/2.9%E2%80%B3-EL029H3WRA

**Comment by jonasniesner** [comment]
It looks like another MCU is used here

**Comment by jjwbruijn** [comment]
Yep, this one isn't supported. Looks like a capable chip, but I don't see this one getting support anytime soon

**Comment by nikkisstuff** [comment]
Can anyone recommend a replacement driver board?
