### ISSUE TITLE
schematic for yellow ap needed 

### ISSUE THREAD

**Issue by nikkisstuff** [jjwbruijn/OpenEPaperLink#228]
Is there a schematic for the yellow ap as there are no component marking on the silkscreen.
![YellowAP_pcb_top](https://github.com/jjwbruijn/OpenEPaperLink/assets/77486170/da30b30e-b338-46b0-b730-b571922349f3)

**Comment by nikkisstuff** [comment]
Is this correct?

![YellowAP_pcb_top_value](https://github.com/jjwbruijn/OpenEPaperLink/assets/77486170/4e05253e-6d4b-4621-a582-76e0c8bd46f2)

**Comment by atc1441** [comment]
It is :)

**Comment by nikkisstuff** [comment]
Fantastic thank you!
