### ISSUE TITLE
Feature request: 90° rotation for Solum 7.4"

### ISSUE THREAD

**Issue by tscharly** [jjwbruijn/OpenEPaperLink#229]
Please add 90° rotation of output for the 7.4 Solums

**Comment by jjwbruijn** [comment]
We're not going to ask the tag to solve this issue :) This needs to be done on the ESP32

**Comment by nlimper** [comment]
For the build in content, that would take all templates to be defined twice. Not planned.
When pushing a jpeg image: you can rotate the image during generation, before pushing to the AP.
When using a json template: you ca use the 'rotate' command. https://github.com/jjwbruijn/OpenEPaperLink/wiki/Json-template#rotate-screen
