### ISSUE TITLE
Programming Wemos S2 mini as tag flasher fails

### ISSUE THREAD

**Issue by Calimerorulez** [jjwbruijn/OpenEPaperLink#230]
Hi,

I'm trying to flash a Wemos S2 mini as a tag flasher, but install.openepaperlink.de throws an error after the flashing process:

`Timed out waiting for packet header`

What am I doing wrong?

**Comment by jonasniesner** [comment]
Did you press and hold the IO/0 button and pressed reset once? Did you use windows or Linux?

**Comment by Calimerorulez** [comment]
Yes I did. I've tried Windows and MacOS. If I flash the blink example via Arduino IDE, all works fine, but as soon as I try to use the site, it gives the error.

**Comment by loomyloon** [comment]
I have the same problem. Can anyone help how to flash Tag 1.54 using ESP32-S2 vemos mini? Well thank you

**Comment by Calimerorulez** [comment]
Now trying a Lolin 32 Lite, and I get `unsupported device`

**Comment by ferrexevi** [comment]
After flashing everything seems correct, but on the label it appears as restored, it does not show AP, however in the browser I can see the following:
![Captura de pantalla 2024-02-23 a las 12 40 08 a  m](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/6faedda9-dcdd-4630-b746-cf773ad23fdd)
No consigo que muestre tenxto en el epaper

**Comment by loomyloon** [comment]
Flashing ESP on the AP is unnecessary. This does not work for flashing the Tag. That won't work.

**Comment by ferrexevi** [comment]
> Flashing ESP on the AP is unnecessary. This does not work for flashing the Tag. That won't work.
How should it happen for it to work? I have another label without disassembling.

The AP is used to be able to write on the labels, right? but what is the process to flash the labels? that is not explained.
thanks

**Comment by Calimerorulez** [comment]
Ok, connected my Wemos S2 Mini to a Linux pc. Installed platformio, cloned this Git repository. Ran the following platformio run command in the Tag_Flasher/ESP32_Flasher/ folder (specific for my situation):

`platformio run --target upload --upload-port /dev/serial/by-id/usb-WEMOS.CC_LOLIN-S2-MINI_0-if00`

I so got my Wemos flashed. Now trying to flash a tage ;)

> > Flashing ESP on the AP is unnecessary. This does not work for flashing the Tag. That won't work.
> > How should it happen for it to work? I have another label without disassembling.
> 
> The AP is used to be able to write on the labels, right? but what is the process to flash the labels? that is not explained. thanks

https://github.com/jjwbruijn/OpenEPaperLink/tree/master/Tag_Flasher explains it very briefly.

**Comment by ferrexevi** [comment]
> Ok, connected my Wemos S2 Mini to a Linux pc. Installed platformio, cloned this Git repository. Ran the following platformio run command in the Tag_Flasher/ESP32_Flasher/ folder (specific for my situation):
> 
> `platformio run --target upload --upload-port /dev/serial/by-id/usb-WEMOS.CC_LOLIN-S2-MINI_0-if00`
> 
> I so got my Wemos flashed. Now trying to flash a tage ;)
> 
> > > Flashing ESP on the AP is unnecessary. This does not work for flashing the Tag. That won't work.
> > > How should it happen for it to work? I have another label without disassembling.
> > 
> > 
> > The AP is used to be able to write on the labels, right? but what is the process to flash the labels? that is not explained. thanks
> 
> https://github.com/jjwbruijn/OpenEPaperLink/tree/master/Tag_Flasher explains it very briefly.

In that schematic I am missing pin number 9, which connects to pin 40 of the wemos, it mentions using the "tak flasher" as I showed in my previous comment, but that did not work...

**Comment by Calimerorulez** [comment]
> > Ok, connected my Wemos S2 Mini to a Linux pc. Installed platformio, cloned this Git repository. Ran the following platformio run command in the Tag_Flasher/ESP32_Flasher/ folder (specific for my situation):
> > `platformio run --target upload --upload-port /dev/serial/by-id/usb-WEMOS.CC_LOLIN-S2-MINI_0-if00`
> > I so got my Wemos flashed. Now trying to flash a tage ;)
> > > > Flashing ESP on the AP is unnecessary. This does not work for flashing the Tag. That won't work.
> > > > How should it happen for it to work? I have another label without disassembling.
> > > 
> > > 
> > > The AP is used to be able to write on the labels, right? but what is the process to flash the labels? that is not explained. thanks
> > 
> > 
> > https://github.com/jjwbruijn/OpenEPaperLink/tree/master/Tag_Flasher explains it very briefly.
> 
> In that schematic I am missing pin number 9, which connects to pin 40 of the wemos, it mentions using the "tak flasher" as I showed in my previous comment, but that did not work...

I'm using that schematic, and just reflashed my zbs-tags succesfully. Pin 9 is optional by the way, but I'm using that. I do not really understand what you mean, so it's difficult for me to help you.

**Comment by ferrexevi** [comment]
> I'm using that schematic, and just reflashed my zbs-tags succesfully. Pin 9 is optional by the way, but I'm using that. I do not really understand what you mean, so it's difficult for me to help you.
I use a translator, sorry, I will try to express myself in the best way possible.

I have those two tags in the photo above, and I used the website's tag flasher and it gave me an error, and I tried it with a Linux environment, but without success.

Could you explain the steps to follow? Do you use Wemos Mini S2 like the one in the image?

The AP is necessary to write to other tags, right? Can I have an AP without a screen? Really, the one that sends the data to the other tags is the tag that is soldered to the wemos, right?

The objective of this is to be able to write my own text on the labels, how should I proceed? I followed this tutorial without success:

https://www.youtube.com/watch?v=8oQdo9bJ7Rk

Thanks for your time

**Comment by ferrexevi** [comment]
I am reviewing this, and on pin number 8 MOSI, I do not have that pin, either that scheme is not for my model or my model does not have that connection....
![Captura de pantalla 2024-02-23 a las 9 17 57 p  m](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/f35c5906-21b1-4d12-abcb-86f2120f4216)
![thumbnail_IMG_9354](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/e5dc1812-5e86-4f45-a603-e8800ce4da95)
I'm stuck, I don't know how to continue...

**Comment by ferrexevi** [comment]
I bring news, this time the pinout has inscriptions, which is every pinout.

How do I know what protocol it uses? What would be the steps to follow to write data to this label? Will it use the same protocol as the previous one? The connection seems to be the same.

![thumbnail_IMG_9360](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/69c2ea8a-ff05-42ec-bede-4e443fa22ade)

The brand is also registered SOLUM MODEL ELD58R2CRN
