### ISSUE TITLE
Missing Miso Pad on SLT-EM1043

### ISSUE THREAD

**Issue by tjspacelord** [jjwbruijn/OpenEPaperLink#234]
Hello,

today I was looking to make a mini AP and stumbled upon a little Problem.
I was opening the Segmented Display and there were 11 pads and not 12 like in all the Documentation. I saw that I have an SLT-EM1043 and not a SLT-EM104, that model seems to have only 11 pads. Does somebody knows if it is possible to use this tag for a Mini AP. If yes what would be the pinout for this model, assuming the pinout is identical to the SLT-EM104 tag, then the Miso Pad is missing. And it seems like an important connection.
Here is a picture of the Segmented Display, where the pad is missing.
![PXL_20240220_123115492 MP](https://github.com/jjwbruijn/OpenEPaperLink/assets/160608192/9788bcba-f8b5-435c-9557-0092f1da59b1)

Thank you all in advance (This Project is awesome)

**Comment by jjwbruijn** [comment]
Interesting! This is a nRF-based segmented tag, which uses a different pinout. While there is support for an nRF based AP, I advise you to build something using an ESP32 C6 or zbs243 based AP instead, as they’re well tested and work with current releases of the AP firmware. I recall there were some range-issues with the nRF AP too…

**Comment by jjwbruijn** [comment]
Also, if you want to trade one of these tags for a well supported one, send me a message on discord. I’d like to bring support for segmented tags one day, including this nRF one (should be easy as we already have a universal firmware for the nRF based tags)
