### ISSUE TITLE
Feature request: control "No updates between" from HA

### ISSUE THREAD

**Issue by HenkeGoransson** [jjwbruijn/OpenEPaperLink#258]
It would be awesome to be able to "pause" tag updstes from HA. 
This way you can pause the tags when you are not home. And save a lot of battery. 

The feature already exists in the AP config as "No updates between".

**Comment by jonasniesner** [comment]
I will close this here as the feature request already exist in the HA integration repo https://github.com/jonasniesner/open_epaper_link_homeassistant/issues/123
