### ISSUE TITLE
Sorry, not bug, need help!

### ISSUE THREAD

**Issue by ferrexevi** [jjwbruijn/OpenEPaperLink#260]
I have hanshow stellar pro tags, according to the videos on YouTube, they refer to these tags, but I can't get them to work.

I soldered the RXD, TXD, GND and VCC, which according to the schematic, are mandatory.

My intention with this is to create a NANO AP, and from that, be able to write to the other tags, which I suppose I will also have to flash, but I can't even make the AP work, except for a single tag, I also tried flashing using the Tag option Web flasher, no result.

Any ideas? suggestion? How should I proceed to get to use them?

![IMG_9382](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/f23c59fc-a725-42f2-8f54-0697cd0cdfb7)
![IMG_9381](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/7349e89e-8456-4825-8b6e-b0f53eefc914)

Use the following links to proceed:

https://www.youtube.com/watch?v=8oQdo9bJ7Rk
https://github.com/jjwbruijn/OpenEPaperLink/blob/master/Tag_Flasher/README.md

Thanks for your time

**Comment by jonasniesner** [comment]
I am sorry to tell you but you will not be able to create a Nano AP with a hanshow tag and the tag tag flasher will also not work for this tag. And you have a size that has no working drivers yet to my knowledge. Please refer to this video https://youtu.be/WRfZJ4xyYwc?si=urC03EO9kCdqfLZs on how to flash them and try to get an ESP32-C6 based AP like the yellow AP

**Comment by ferrexevi** [comment]
> I am sorry to tell you but you will not be able to create a Nano AP with a hanshow tag and the tag tag flasher will also not work for this tag. And you have a size that has no working drivers yet to my knowledge. Please refer to this video https://youtu.be/WRfZJ4xyYwc?si=urC03EO9kCdqfLZs on how to flash them and try to get an ESP32-C6 based AP like the yellow AP

Yes, I saw this video, it uses only 3 pins, that confused me. I'll look at it again and see if I can do something. Maybe they are too new to be able to write in them. thank you!

**Comment by nlimper** [comment]
What you have to write in them, is a piece of software. The software should of course match the hardware. It's not a question of 'too new'. But nobody created software for that tag yet. So, you cannot use it.

**Comment by ferrexevi** [comment]
> What you have to write in them, is a piece of software. The software should of course match the hardware. It's not a question of 'too new'. But nobody created software for that tag yet. So, you cannot use it.

ok, we will have to wait, if my labels help someone for research to create that software, here I am.

Thank you!
