### ISSUE TITLE
Support for EL029H4WRC?

### ISSUE THREAD

**Issue by cgommel** [jjwbruijn/OpenEPaperLink#261]
I could probably get some of the mentioned tags.

Is there any support for them in sight? 

The internals [look quite different](https://fcc.report/FCC-ID/2AFWN-EL029H4WRC/4788168.pdf
) - much smaller PCB. 

Do not have devices yet and cannot answer you what Wireless SoC is used.

**Comment by jjwbruijn** [comment]
Not going to bet my life savings on it, but this tag looks Realtek, unsupported for now. But you won't know until you open it up! Tags with similar ID's have been using different SoC's anyway so based on the ID alone, it's hard to tell.

**Comment by BigSpice** [comment]
Got a bunch of documentation on this specific tag.
Attached below.

Also some custom work im trying to do. would love some pointers if im going about my quick pcb connections correctly.

Trying to follow https://github.com/atc1441/ATC_TLSR_Paper & https://javabin.cn/2022/epaper.html
However, I can only reset the display through my FTDi connector. 
![image](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/f88717de-9c57-4a8b-abe4-dda2ac5a42d3)
![image](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/66e89b07-1049-4868-9c34-3e42a3bc4c8f)


1.6"
![image](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/bfd9ba5b-0cda-4c54-a197-ce5d5ea2dd9b)
![20240629_172915](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/1557e916-ad9e-4394-8ee4-09b91491d3c3)
![20240629_172857](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/ea1d6a18-f6e5-42dd-a278-0c38c9e51c8d)
2.2"
![image](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/1e631945-2564-4eb7-9a1d-cba133b03c0f)
![20240629_172749](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/fdd13dce-8fb3-4c2d-a199-d889e8455924)
![20240629_172650](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/23240514/f3aac771-6a2a-4b67-96f4-3cdf66190a4f)
