### ISSUE TITLE
Feature request: Password Protected Admin-page. 

### ISSUE THREAD

**Issue by frodr1k** [jjwbruijn/OpenEPaperLink#264]
**Is your feature request related to a problem? Please describe.**
Lack of security. The admin page should at least be protected by a login 

**Describe the solution you'd like**
The AP needs some kind of password protection at least. In the long term we should run some kind of shakedown of the AP to find and fix other vulnerabilities. But first things first. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jjwbruijn** [comment]
Please only use an OEPL AP on a network you have control over.

A 'shakedown' of the AP isn't necessary. It's unsecured. It's not meant to be used on a 'public' network. Security of a device like this was never a goal, and any attempts to make it 'safe' will generally be laughable.

Even if you would secure the webserver, the AP uses unencrypted/unauthenticated multicast packets to sync state to other potential accesspoints. A DoS attack on an ESP32 doesn't require a whole lot of traffic and would also disturb the functioning of the accesspoint.

Furthermore, the 802.15.4 protocol used by OEPL is fully unencrypted and unauthenticated, which means it can be spoofed easily. If this is a concern, a different solution might be more fitting for you.
