### ISSUE TITLE
Support for Sub-GHz Devices (e.g. EL029D3WRA)

### ISSUE THREAD

**Issue by cgommel** [jjwbruijn/OpenEPaperLink#268]
currently there are many of them available on ebay (germany).

I purchased two samples and took one apart: Uses the CC1310 Sub-GHz-SoC

So this is definitely incompatible....

Do you intend to support these 868 MHz devices?

**Comment by jjwbruijn** [comment]
Yes! Although the first target will be CC1110 based Chroma devices, later on CC1310 can be supported, if someone takes it upon themselves to write support. No timeline, it'll be done when it's done!

**Comment by user45876** [comment]
As I do not want to open up a new issue - are there any news regarding this? Unfortunately I am failing miserably flashing this.
