### ISSUE TITLE
M2 tags color red not as red af before after fw update.

### ISSUE THREAD

**Issue by Calimerorulez** [jjwbruijn/OpenEPaperLink#269]
Hi,

Just updates my M2 tags to fw 27 (the latest) and now the color red is much more dark than before.

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/1130552/0469540f-6745-4dc9-8659-da09a76dda5f)

**Comment by jonasniesner** [comment]
That is normal because a short lut gets used for some updates to save power. To "prevent" this, you can set the full LUT in the AP. If that doesn't help, feel free to reopen your issue.
