### ISSUE TITLE
Price tag address changed?

### ISSUE THREAD

**Issue by ov1d1u** [jjwbruijn/OpenEPaperLink#272]
One of my price tag had low battery. I replaced the battery but it took me a few tries because the batteries were losing contact as I tried to put the cover back. Because the tag was in sleeping state after installing the batteries, I even shorted out the battery terminals (as instructed). Now it looks like the tag's MAC address changed, it was `0000021b0a593b19` but now it is `0000ffffffff3b19`. Did I do some kind of reset  while I was trying to put the cover back or is it expected for the address to change when shorting out the battery terminals?

**To Reproduce**
1. Remove the batteries
2. Be clumsy while installing the new batteries
3. Maybe even try to reset the tag by shorting the battery terminals

**Expected behavior**
The tag's address should not change

**Screenshots**
<img width="711" alt="Screenshot 2024-03-14 at 09 59 32" src="https://github.com/jjwbruijn/OpenEPaperLink/assets/1385202/45097cce-d26e-49d9-bde0-acf03f646122">
The leftmost tag is essentially the same with the rightmost one

**Comment by jjwbruijn** [comment]
I'm afraid you discovered a hardware voltage glitch! There isn't a whole lot we can do about this; if you run a microcontroller on a bad power supply, it can do all kinds of weird things. Since we don't have proper brown-out detection, there isn't much we can do to fix this.
