### ISSUE TITLE
OpenEPaperLink Mini-AP v4 instability issue

### ISSUE THREAD

**Issue by timoknapp** [jjwbruijn/OpenEPaperLink#276]
**Describe the bug**

Hi @nlimper 

I bought the [Mini-AP](https://www.tindie.com/products/electronics-by-nic/openepaperlink-mini-ap-v3-zigbee-wifi-gateway/) plus a few tags in your shop. After a while I noticed that the [Mini-AP](https://www.tindie.com/products/electronics-by-nic/openepaperlink-mini-ap-v3-zigbee-wifi-gateway/) is not running stable, its is either restarting in a weird pattern or being stuck in a failed state (red led). When unplugging / replugging the power it is sometimes healing itself but mostly it its not. I have the feeling that there is a loose contact or something at the usb connector (see video). I tried multiple cables and plugs but always the same issue.

I also updated the Firmware of the AP to most recent v2.52 but unfortunately it didnt resolve the issue. I uploaded a few videos and a photo that shows the issue.

https://1drv.ms/f/s!AgYrLuhUCZm4gZQzzozUaIo_O2r3Hw?e=hhL7r9

I hope that you can help me resolving it. 
Best,
Timo

**To Reproduce**
Please have a look into my video attached.

**Expected behavior**
Mini-AP running continuously in a correct state while being plugged into power

**Screenshots**
Mini-AP stuck in failed state:

![epaper-mini-ap-v4](https://github.com/jjwbruijn/OpenEPaperLink/assets/11437666/dde9f89e-d6de-4bc0-a1d9-50ad3d59906d)

**Comment by nlimper** [comment]
That's a hardware problem. I will reply to your message shortly.
