### ISSUE TITLE
Red No longer Displayed Correctly - Version 2.5 AP Firmware

### ISSUE THREAD

**Issue by Boh1** [jjwbruijn/OpenEPaperLink#277]
After updating my AP from 2.5-beta 3 to 2.52, my tags no longer render red correctly - it comes out as a light grey. 

This is on a M2 2.9" tag with new batteries and firmware 19 0x13. Verified on a second tag.

Reverting the AP back to 2.5-beta3 fixes the issue.

**Comment by jjwbruijn** [comment]
Sounds like you discovered partial LUTs! Try setting the tag to 'Always Full LUT' in settings for the relevant tag. This forces a full refresh cycle, and makes sure the tag displays red properly. Some tags deal with partial LUT's better than others
