### ISSUE TITLE
Stupid question: How to set tag content with newer FW

### ISSUE THREAD

**Issue by emufan** [jjwbruijn/OpenEPaperLink#289]
**Describe the bug**
I updated from 2.01b to 2.5.2

But where can I set now the content of the tags?

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/22775515/96abef30-3631-406b-8eac-26ec968769c0)

If have onle the content in AP display anymore.

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/22775515/9bf8503b-a68d-42c1-b1f1-f329afe26b9f)

**Comment by nlimper** [comment]
empty your browser cache, as it misses some important info in the tag types on setting the content.
You can instead also open the development window (ctrl-shift-J in Chrome), disable cache in the network tab, en reload the webpage to make sure your browser loads the latest files.

**Comment by emufan** [comment]
Solved with this. Thank you!
