### ISSUE TITLE
Wind direction icon is 180 degrees off

### ISSUE THREAD

**Issue by bartbh** [jjwbruijn/OpenEPaperLink#29]
The icon displaying the wind direction is 180 degrees off. A wind of 90 degrees means wind coming from the east, blowing to the west. So an arrow starting at 90 degrees (east) and pointing toward 270 (west).

https://github.com/jjwbruijn/OpenEPaperLink/blob/2060edb54c1528a21f87024fe54d82542fbc1867/ESP32_AP-Flasher/src/contentmanager.cpp#L1003

Suggestion would be to shift the wind direction index (8 directions) by 4
```suggestion
    String directions[] = {"\uf058", "\uf087", "\uf048", "\uf043","\uf044", "\uf088", "\uf04d", "\uf057"};
```

**Comment by jjwbruijn** [comment]
Thank you!
