### ISSUE TITLE
changing Mac-adress with oepl-flasher.py wont work

### ISSUE THREAD

**Issue by micklafisch** [jjwbruijn/OpenEPaperLink#293]
**Describe the bug**
changing the Mac address on a Solum ST-GR29000 with the oepl-flasher.py will fail

**To Reproduce**
1. read the infopage from a flashed tag
(command: python OEPL-Flasher.py -t 192.168.12.173 -i -z read readout1_infopage.bin)
2. check the .bin at 0x10 for the correct Mac
3. write the same infopage (or edit the 0x10 address for an own Mac) to another flashed tag
 (command: python OEPL-Flasher.py -t 192.168.12.173 -i -z write readout1_infopage.bin)
4. Mac address will be not the same as expected
(command python OEPL-Flasher.py -t 192.168.12.173 -i -z read readout2_infopage.bin)

**Expected behavior**
writing a Mac address to a flashed tag

**Additional context**
Tested with AP v4 (V2.52)  and Solum M2 Tags (Firmware SOL_M2_29_SSD_0027.bin). both readouts are attached. 
[readout bin.zip](https://github.com/jjwbruijn/OpenEPaperLink/files/14932187/readout.bin.zip)

**Comment by jjwbruijn** [comment]
Thx, please confirm which exact commands you used to read/write the infopage, and add the resulting binary to the ticket

**Comment by micklafisch** [comment]
i edited the description with the informations

**Comment by jjwbruijn** [comment]
The commands you used are correct. I've been unable to reproduce the issue, I've successfully edited the infopage on a ZBS-based tag on 2.52.

- Problem in wiring to your tag
- Problem with the tag itself
