### ISSUE TITLE
Buienradar seems broken/has wrong text

### ISSUE THREAD

**Issue by marcovannoord** [jjwbruijn/OpenEPaperLink#312]
**Describe the bug**
It seems that for about a week or so, the buienradar image generation seems to produce a wrong image. The graph keeps indicating no rain expected and there is some extra text at the bottom that i can't fully make sense of.
I tried this for different locations in the Netherlands, using a M2 2.9" display. 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="106" alt="image" src="https://github.com/jjwbruijn/OpenEPaperLink/assets/90630/9ed78588-4df2-4825-97e3-9d049f39e85f">

**Additional context**

**Comment by nlimper** [comment]
‘Nederland’ is a place name in the USA. Please try with a valid Dutch city name. 
other than that, sometimes the Buienradar API is broken for a few days. That’s out of our control.

**Comment by PieterBoeren** [comment]
I have exact the same issue, with a normal Dutch location (Hooglanderveen), it's broken for over a week now (it did work when it was raining last week). It looks exactly like the screenshot above.

**Comment by kvandt** [comment]
Same here for Soesterberg

**Comment by nlimper** [comment]
Buienradar made a change to their API. :-(
Fixed!
https://github.com/jjwbruijn/OpenEPaperLink/commit/73db8d52a88260640b7252a382410c26c9ceec2c

**Comment by kvandt** [comment]
Just compiled a new bin file with this fix. Works great again.
