### ISSUE TITLE
New Label free protocol?

### ISSUE THREAD

**Issue by ferrexevi** [jjwbruijn/OpenEPaperLink#321]
I have this labels that I got in a second-hand market, I bought it to avoid it, and my surprise was to see that it has a SLOT for a microcontroller (bios style?). Features a "G1 retail red NFC imagotag" tag

Does not present any manufacturing date

![IMG_9736](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/16521731-70f4-4855-acd5-08aeaf4788dc)

![IMG_9734](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/743356a1-cc89-4680-bbf9-726233226391)

Both are from the same "brand", although they have different aesthetics.

![IMG_9739](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/a1cc5d52-748f-4aed-8fb1-c464976b8f33)

![IMG_9737](https://github.com/jjwbruijn/OpenEPaperLink/assets/31113439/c6c79cc3-5711-471f-8463-662592a80e1f)

According to what I found online, they seem to be labels from 2017, but they do have a very sun-faded color tone, which indicates that they seem to be very old.

From what I have been able to read, it runs on a software called JEEGY. I will update the post with all the information I can provide about these labels, to see if this helps and something can be achieved. Sorry for my bad English, I'm using a translator.

thanks for your time

PD: Sorry, just let me choose between improvement or bug to create the post

**Comment by atc1441** [comment]
Hey, this brand is not and will not be supported
