### ISSUE TITLE
"Insufficient EXTERNAL RAM memory" when trying to build AP Firmware for zbs_segmented_uk tag

### ISSUE THREAD

**Issue by bobiboy** [jjwbruijn/OpenEPaperLink#323]
**Describe the bug**
Whenever I try to run 

`make BUILD=zbs_segmented_uk CPU=8051 SOC=zbs243`

to build the AP firmware for the segmented tag, I'm getting the following error message:

> rm -f main.ihx
sdcc main.rel comms.rel APDisplay.rel barcode.rel emulateTag.rel soc/zbs243/soc.rel soc/zbs243/wdt.rel soc/zbs243/sleep.rel soc/zbs243/spi.rel soc/zbs243/uart.rel soc/zbs243/timer.rel soc/zbs243/radio.rel soc/zbs243/flash.rel soc/zbs243/temperature.rel cpu/8051/random.rel cpu/8051/aes.rel cpu/8051/printf.rel soc/zbs243/i2c.rel cpu/8051/asmUtil.rel cpu/8051/cpu.rel board/zbs_segmented_uk/board.rel board/zbs_segmented_uk/screen.rel -DAP_FW=1 --code-size 0xfc00 -Isoc/zbs243 -DSOC_ZBS243 --xram-loc 0xe000 --xram-size 0x2000 --model-large -Icpu/8051 -mmcs51 --std-c2x --opt-code-size --peep-file cpu/8051/peep.def --fomit-frame-pointer -Iboard/zbs_segmented_uk -Isoc/zbs243 -Icpu/8051 -I.

>?ASlink-Error-Insufficient EXTERNAL RAM memory.
make: *** [Makefile:38: main.ihx] Error 1

Any idea what I'm missing? 

**To Reproduce**
1. Clone the repository (`git clone https://github.com/jjwbruijn/OpenEPaperLink.git`)
2. `cd OpenEPaperLink/zbs243_AP_FW`
3. `source ../sdcc/setup_sdcc.sh`
4. `ln -s **PATH_TO_CLONED_REPO**/zbs243_Tag_FW/aes.h cpu/8051/.`
5. `make BUILD=zbs_segmented_uk CPU=8051 SOC=zbs243`

**Expected behavior**
I'd expect the FW to be built without errors

**Screenshots**

**Additional context**
I'm trying set up my environment to be able to build my own AP firmware, as I have the "german" variant of the Segmented Tag and while the UK Firmware seems to work for the radio side of things, it is not driving the display correctly (segments starting from bottom right instead of top left and some characters are flipped (and some are completely wrong)). I used the provided script to set up sdcc and got it to compile properly. 
When I tried to run 

`make BUILD=zbs_segmented_uk CPU=8051 SOC=zbs243`

for the first time, it was missing the "aes.h" file in referenced in "cpu/8085/aes.c". I linked it from the zbs_243_Tag_FW folder (not sure if that was correct) to resolve the issue.

Thanks in advance for any support!

**Comment by jjwbruijn** [comment]
Fixed, moved to the ZBS243 repo here:
https://github.com/OpenEPaperLink/Tag_FW_ZBS243
