### ISSUE TITLE
Feature request: IO pin configuration with the config page

### ISSUE THREAD

**Issue by jonasniesner** [jjwbruijn/OpenEPaperLink#38]
It would be useful if the IO configuration could be changed in the web interface. This new configuration could be stored in the db

**Comment by jjwbruijn** [comment]
Making this dynamic would add overhead and will probably hurt performance.

Also, this is something you set once, and keep it like that. Pinouts shouldn't change, if they work...

**Comment by jonasniesner** [comment]
Ok, i will close it then
