### ISSUE TITLE
Feature request: Round temperature values (less updates for Current Weather)

### ISSUE THREAD

**Issue by heringa** [jjwbruijn/OpenEPaperLink#382]
**Is your feature request related to a problem? Please describe.**
Yes. The temperature with 1 decimal leads to frequent updates which leads to a significant decrease of battery lifetime.

**Describe the solution you'd like**
Round the temperature to whole integer values should lead to less updates.
Alternative: configure a minimal update timeout. eg. 15 min.

**Describe alternatives you've considered**
I bought and replaced batteries over and over. ;-)

**Additional context**
The rounding feature could be optional.

**Comment by nlimper** [comment]
The update frequency of the current weather is once every half hour.

But agree, it would be better to make the refresh frequency configurable, just like the weather forcast (it's faily easy: use the exiting 'interval' variable by copying lines https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/ESP32_AP-Flasher/src/contentmanager.cpp#L346-L347 to https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/ESP32_AP-Flasher/src/contentmanager.cpp#L339-L340 and add it as a parameter in content_cards.json just like https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/ESP32_AP-Flasher/src/contentmanager.cpp#L346-L347)

(sorry, I currently cannot do it myself, but if somebody feels like it: go ahead!)

**Comment by nlimper** [comment]
fixed, in https://github.com/OpenEPaperLink/OpenEPaperLink/commit/dd5d96d1ee9a20d5012156d531b6c5550adb9139
