### ISSUE TITLE
Feature request: Add zipped files of the web pages to the filesystem image

### ISSUE THREAD

**Issue by jonasniesner** [jjwbruijn/OpenEPaperLink#39]

**Comment by jonasniesner** [comment]
@nlimper Already planned for the next weekend

**Comment by jonasniesner** [comment]
I can implement it, however, it will always show the new files as a push. That is why i think it only makes sense to run it on every release. @nlimper do you think this would be reasonable.

**Comment by nlimper** [comment]
yes, just at the release is fine. 
Only thing is, sadly gzip insert to time or something in a gzipped file, so even if the source is not changed, it results in a different gzipped file every time, and github shows it as changed file. Maybe you can find a solution for that?

**Comment by jonasniesner** [comment]
Implemented
