### ISSUE TITLE
Feature request: Enable roaming between multible APs

### ISSUE THREAD

**Issue by jonasniesner** [jjwbruijn/OpenEPaperLink#44]
I don't know if this is even possible but would be useful for events with a lot of moving tags.

**Comment by nlimper** [comment]
The tag already switches over to a different AP if it cannot communicate with the associated AP for a long time. But for a real roaming experience, the tag should do a scan of the channels much more often, that will drain de battery quickly.
Of course, the timings for determining if the current AP cannot be reached can be set tighter. At the moment it's at least 8x 10 minutes if I understand the code right. @jjwbruijn probably knows the reasons behind that, and the implications of lowering the timings.

**Comment by jjwbruijn** [comment]
This is now configurable in the latest tag FW with config options
