### ISSUE TITLE
same weblink on multiple displays - update problems

### ISSUE THREAD

**Issue by eokgnah** [jjwbruijn/OpenEPaperLink#53]
If i have the same url on several displays the update procedure is buggy.

for example:
1. display 1 = http://myserver.com/image.jpg (versionA)
   display 2 = http://myserver.com/image.jpg (versionA)
2. i start both displays initially and they both get the (versionA) picture.
3. i update my image.jpg on my server to (versionB).
4. for example display1 checks in and sees "there is a new image" (versionB), downloads it and displays it.
5. then after some time display2, who has still (versionA) on it checks in.
   The server looks at my server and compares it to the locally stored.
   (Server and ESP have versionB)
   so it decides (wrongly) to do nothing!
6. the display who is 2nd (or more) in line is stuck with the old image and never gehts a update.
   
Can the esp keep track which picture version on which display is?
Then it can decide if the picture needs an update, because the local picture is newer then the picture on the display, even if the local cached picture is the same then the one on the webserver.

**Comment by nlimper** [comment]
Nothing gets cached. The last fetched date of an image is kept with the data of a specific tag, and send along with a 'if-modified-since' header, to let your server determine if a new image is needed. But I will look into it.
I'm assuming you're running the latest version of the esp32 firmware.

**Comment by nlimper** [comment]
fixed. There as a bug in the If-Modified-Since-header.
https://github.com/jjwbruijn/OpenEPaperLink/commit/db88de1f7549a2be64733ff80ff1fcf94813ff54
