### ISSUE TITLE
Feature request: Documentation : How to build an Image

### ISSUE THREAD

**Issue by JpEncausse** [jjwbruijn/OpenEPaperLink#55]
**Describe the solution you'd like**
Improve the documentation to explain how to build an Image to be summited to a tag via URL

**Additional context**
I use Photopea to change an image I found in the repository, save it back in jpg.
- It works but the red (255,0,0) is not as red as in the Date/TIme feature
- May be PNG is better ? And/Or set less color in the encoding ?

**Comment by nlimper** [comment]
This is imho as clear as it gets:
https://github.com/jjwbruijn/OpenEPaperLink/wiki/Image-specifications
and
https://github.com/jjwbruijn/OpenEPaperLink/wiki/Image-upload

If you like to use other tools to build an image, I can make an example, in that case tell me which tools you want to use.
Using PNG makes no difference. It's much harder to decode, the ESP32 doesn't have the space anymore, and it doesn't improve anything.
The tag can have three colors: black, white and red. There are no different kinds of red to be send. The 'redness' of a pixel depends also on temperature, production batch and age of the tag. That part is quite analogue, but not (easily) possible to change. At least not in image file.

If the picture you generated is different than expected, send an example here, and I can look into it. :-) For example, if the red is pixelated and if that's unwanted, turn off dither.
