### ISSUE TITLE
Tags-specs page is missing

### ISSUE THREAD

**Issue by seeers** [jjwbruijn/OpenEPaperLink#56]
the excellent documentation on the Tags-specs page is unfortunately no longer available. Would you provide it again? 
https://github.com/jjwbruijn/OpenEPaperLink/blob/master/Tags-specs/

**Comment by jonasniesner** [comment]
Did you check the wiki? I think it was moved there.

**Comment by seeers** [comment]
Thank you. I have changed it in the readme and created a PullRequest.
