### ISSUE TITLE
Only ASCII characters in RSS-Feeds on tags

### ISSUE THREAD

**Issue by DL5SMB** [jjwbruijn/OpenEPaperLink#60]
It seems that RSS feeds as content for the tags only show standard ASCII characters
and do take any encoding into account.

I tried two different German RSS feeds, both encoded with UTF-8
[Tagesschau](https://www.tagesschau.de/infoservices/alle-meldungen-100~rss2.xml)
[Spiegel](https://www.spiegel.de/schlagzeilen/tops/index.rss)

In both feeds all German umlauts / special characters (ä,ö,ü,ß etc.) are being ignored/omitted.

**Comment by nlimper** [comment]
Already fixed 5 days ago duting rehaul of contentmanager, in commit https://github.com/jjwbruijn/OpenEPaperLink/commit/c68b582be7841a113ac7bf45c604a7c9b6f0f77f
Will do a new release shortly.
