### ISSUE TITLE
Feature request: show current firmware version of the

### ISSUE THREAD

**Issue by bartbh** [jjwbruijn/OpenEPaperLink#62]
If I'm correct, the current firmware version of a tag is only shown during boot. Maybe it is possible to show the firmware version on the AP website? So then you can figure out which tag is running which (outdated) firmware and maybe needs a firmware update.

**Comment by jonasniesner** [comment]
This enhancement is similar to #45

**Comment by jjwbruijn** [comment]
Done in https://github.com/jjwbruijn/OpenEPaperLink/commit/da6d783e3b494f92f40a1d23e00c7189ddda2679
