### ISSUE TITLE
cant upload  the AP to the Esp32. Filesystem missing

### ISSUE THREAD

**Issue by Smoeller0** [jjwbruijn/OpenEPaperLink#73]
Hello i clone this code, Open ESP32_AP-Flasher in the visual studio code and upload. its nearly successful. But after the Wifi manager it shows "index.html not found. Did you forget to upload the littlefs partition?"
Where can i get this data? 
In the video (https://www.youtube.com/watch?v=Etonkolz9Bs) there is an second upload from the Folder /  Platform / Upload filesystem image. But i cant find this data anymore?

**Comment by jjwbruijn** [comment]
They're found in PlatformIO under actions. As you correctly recognized, this data is required for the AP to work :)
