### ISSUE TITLE
Website sliding around when trying to paint an image manually on mobile phone

### ISSUE THREAD

**Issue by Ennar1991** [jjwbruijn/OpenEPaperLink#80]
**Describe the bug**
When many displays are connected to an AP, editing an image manually (drawing, text) becomes impossible due to the website sliding around instead of pixels appearing on the canvas. Tested with Huawei P20 Pro, Samsung Galaxy Tab A7 in Chrome browser (newest version).

**To Reproduce**
1. Open AP site in mobile phone's browser (in my case Chrome)
2. Open an e-ink display, set to static image
3. edit image manually
4. draw on canvas, the website slides around instead. No pixels appear on canvas.

**Expected behavior**
The website should be locked in place during canvas editing

**Comment by nlimper** [comment]
Thanks for the bug report!
Fixed it, in commit https://github.com/jjwbruijn/OpenEPaperLink/commit/9ef2737bc3fb9a200373db98b23bcced1c2b4f6b
To update, either replace the files in /www-folder using the contentfs editor, or wait until the next release.
