### ISSUE TITLE
Feature request: grouping active tags

### ISSUE THREAD

**Issue by coelner** [jjwbruijn/OpenEPaperLink#84]
**Is your feature request related to a problem? Please describe.**
having a lot of tags (>40) makes it a little bit messy.

**Describe the solution you'd like**
 a simple grouping based on the shown content, the status like 'awaiting update', 'not seen for a long time', 'battery level' and collapse a specific group.

**Describe alternatives you've considered**
using the search provided by the browser

**Additional context**
none

**Comment by nlimper** [comment]
Thanks for the suggestion.
group/sort/filter:
https://github.com/jjwbruijn/OpenEPaperLink/commit/c831f07b6eb47fe9181e78804647b5c3dc94b8c0
