### ISSUE TITLE
Json templates are not cleaned up

### ISSUE THREAD

**Issue by PieterBoeren** [jjwbruijn/OpenEPaperLink#96]
**Describe the bug**
When you once use a Json template on a tag, the file is never cleaned from disk. Maybe it's intended, but since disk space is limited, I would expect "old" json files to be removed once they are no longer in use.

**To Reproduce**
1. Upload a Json template (I used the "jsontemplate-demo.html")
2. Change the config of the tag to something else (weather/current date/etc)
3. Open the file browser and observe the json file still in the root folder

**Expected behavior**
Json files should be removed after they are not used anymore (maybe already after image generation?)

**Comment by nlimper** [comment]
fixed in https://github.com/jjwbruijn/OpenEPaperLink/commit/b4bf060a51009602e1b318db22b1724c14929341
